### ISSUE TITLE
can you make it for the new ionic 2?

### ISSUE THREAD

**Issue by arsewizz** [arjunsk/ionic-firebase-shopping-cart#1]
thisrt i want to say thank you for the great repo, but i need a help with the some kind of apps but with ionic 2!!! can you help me?

**Comment by arjunsk** [comment]
I will be porting this to ionic 2 . But not very soon! Currently I am busy with my academics.  To get the latest updates, just subscribe to my blog.

**Comment by arsewizz** [comment]
ok thanks, i'm continue to wait

**Comment by arjunsk** [comment]
https://github.com/arjunsk/ionic2_firebase_shopping_cart
