### ISSUE TITLE
firebase database url

### ISSUE THREAD

**Issue by lawnet** [arjunsk/ionic-firebase-shopping-cart#11]
},
    "item6" : {
      "available" : true,
      "category" : "cat02",
      "description" : "item6 description",
      "image" : "Smoothie",    //from firebase storage url
      "name" : "Smoothie",
      "price" : 70,
      "stock" : 100
    },

So, here we are calling the image locally, if you want to call the image from any online image link like from the firebase storage. What we have to do?

**Comment by arjunsk** [comment]
You can host the image in S3/firebase-storage, and point to that image url.
