### ISSUE TITLE
sharedUtilsshowLoading not disappear

### ISSUE THREAD

**Issue by tr00869963** [arjunsk/ionic-firebase-shopping-cart#2]
Hello,I just started  learning ionic and I really like your application.
In login page when I don't insert anything  and click login button a showloading keep running.it's not disappear and doesn't show alert until I refresh page
but I can login normaly if I insert true email and password.
can you teach me how to fix this please

**Comment by arjunsk** [comment]
In this project, I have written the code to hide the loading icon. 

Have you configured the app according to this tutorial: 
https://www.youtube.com/watch?v=GKlnjdbmPxU&feature=youtu.be

Will let you know, if i find any bug or fixes !!
