### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by itsmeusama** [arjunsk/ionic-firebase-shopping-cart#3]
Couldn't Login to the app....

**Comment by arjunsk** [comment]
Please see this video: https://www.youtube.com/watch?v=GKlnjdbmPxU

**Comment by itsmeusama** [comment]
thanks for the video thats pretty helpful. <3

**Comment by itsmeusama** [comment]
bro! i just follow the video tutorial and setup the Firebase and login but
i couldn't see anything in the menu (burger photos and etc stuff as it is
shown in your screen shots). why is that?

**Comment by arjunsk** [comment]
Read these articles: http://www.arjunsk.com/tag/shopping-cart/
You will most likely solve your issue.

**Comment by itsmeusama** [comment]
I saw that bro. Login part is ok but once I logged in I couldn't see any
items in menu

**Comment by itsmeusama** [comment]
this is the error bro

ionic.bundle.js:25642 Error: permission_denied: Client doesn't have permission to access the desired data.
    at J (firebase.js:120)
    at Object.J (firebase.js:201)
    at firebase.js:187
    at wh.h.Fd (firebase.js:191)
    at kh.Fd (firebase.js:182)
    at ch.wg (firebase.js:180)
    at fh (firebase.js:174)
    at WebSocket.va.onmessage (firebase.js:173)
(anonymous)	@	ionic.bundle.js:25642
$$error	@	angularfire.min.js:12
(anonymous)	@	angularfire.min.js:12
(anonymous)	@	angularfire.min.js:12
$eval	@	ionic.bundle.js:29158
$digest	@	ionic.bundle.js:28969
(anonymous)	@	ionic.bundle.js:29197
completeOutstandingRequest	@	ionic.bundle.js:18706
(anonymous)	@	ionic.bundle.js:18978

**Comment by arjunsk** [comment]
May be, you didn't set the database rules to auth=true. 

Please refer the video

**Comment by itsmeusama** [comment]
yep bro there was an issue in setting up the firebase. its working now. Thanks a Lot
