### ISSUE TITLE
missing menu

### ISSUE THREAD

**Issue by armgit5** [arjunsk/ionic-firebase-shopping-cart#5]
just wondering how I can add food to menu?
![screen shot 2560-06-18 at 12 45 13 pm](https://user-images.githubusercontent.com/3277669/27258446-bc8eb8cc-5424-11e7-993e-4b5b505b0504.png)

**Comment by arjunsk** [comment]
I think you haven't imported the menu items to your database. 
Refer: https://youtu.be/GKlnjdbmPxU?t=1m36s

/*
This project is currently not maintained as this is outdated(based on ionic 1).
 It is here for reference only.
*/

**Comment by armgit5** [comment]
Thanks a lot Arjun. I really like your project though :-)
