### ISSUE TITLE
Group ordered items under order ID

### ISSUE THREAD

**Issue by chattago2002** [arjunsk/ionic-firebase-shopping-cart#9]
Hi.

I think this project is really simple and cool but needs to some improvements.
For example, I would to group ordered items under a unique "order" (using an order ID); in this way I could monitor a specific order at a time and work to prepare item of the same order before proceed to the following.
Is this an interesting feature for you, to be planned to develop?

P.S. How can I change currency?

Waiting for an answer.
Thanks,
Diego.

**Comment by arjunsk** [comment]
The project is no longer maintained. It is here for educational purpose only.
